#自定义邮件配置
mail:
  sender: #发送者
  recipient: #接收者
  cc: #抄送

#spring发送邮件配置
spring:
  mail:
    default-encoding: UTF-8
    username: #邮箱
    password: #stmp专用密码
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
    host: smtp.qq.com
